### ISSUE TITLE
attribute not saved

### ISSUE THREAD

**Issue by tomas4TW** [umlfri/umlfri2#4]
Project: UML with class diagram
Window/Label: Properties of class
Issue: Addding attribute, name type etc... Then click SAVE. Then close Properties window by clicking X button on top right (closeEvent in QT), and attribute not show in class, it was not saved. Again open Class Properties window -> there is not attribute in list, instead of I clicked SAVE button previously. 

Maybe need to connect closeEvent with OK or Apply button slot? Or some bug in Save button slot? Or this is feature and correct state?

**Comment by janjanech** [comment]
Thank you for your feedback. This behavior is intended. Your changes are not applied until you click the "Ok" or "Apply" button. But I realize now that it might not be expected by a user.
I have changed the dialog closing behavior. If the dialog's data was changed and you close the dialog by clicking the X button, UML .FRI will ask a user what is their expected action: closing with or without applying the changes.
